const fields={tipo:document.getElementById("tipo"),formato:document.getElementById("formato"),pais:document.getElementById("pais"),partner:document.getElementById("partner"),solicitante:document.getElementById("solicitante"),titulo:document.getElementById("titulo"),bajada:document.getElementById("bajada"),cta:document.getElementById("cta"),objetivo:document.getElementById("objetivo"),fechaEvento:document.getElementById("fechaEvento"),horaEvento:document.getElementById("horaEvento"),lugarEvento:document.getElementById("lugarEvento"),producto:document.getElementById("producto"),beneficio1:document.getElementById("beneficio1"),beneficio2:document.getElementById("beneficio2"),beneficio3:document.getElementById("beneficio3"),dia:document.getElementById("dia"),motivo:document.getElementById("motivo"),comentarios:document.getElementById("comentarios"),logoPartner:document.getElementById("logoPartner"),imagenFondo:document.getElementById("imagenFondo")};
const preview={name:document.getElementById("previewName"),market:document.getElementById("marketPreview"),partnerBadge:document.getElementById("partnerBadge"),partnerLogo:document.getElementById("partnerLogoPreview"),bg:document.getElementById("flyerBg"),title:document.getElementById("titlePreview"),subtitle:document.getElementById("subtitlePreview"),cta:document.getElementById("ctaPreview"),details:document.getElementById("detailsPreview"),canvas:document.getElementById("flyerCanvas")};
const resultBox=document.getElementById("resultBox"),sendBtn=document.getElementById("sendBtn"),copyJsonBtn=document.getElementById("copyJsonBtn"),tituloCount=document.getElementById("tituloCount"),bajadaCount=document.getElementById("bajadaCount");
const typeLabels={evento:"Flyer de evento",producto:"Flyer de producto",conmemorativo:"Pieza conmemorativa"};
function normalizeParam(value){return value?decodeURIComponent(value.replace(/\+/g," ")):""}
function loadFromUrl(){const params=new URLSearchParams(window.location.search);const map={template:"tipo",tipo:"tipo",formato:"formato",pais:"pais",partner:"partner",solicitante:"solicitante",titulo:"titulo",title:"titulo",bajada:"bajada",copy:"bajada",cta:"cta",objetivo:"objetivo",fecha:"fechaEvento",date:"fechaEvento",hora:"horaEvento",time:"horaEvento",lugar:"lugarEvento",place:"lugarEvento",producto:"producto",beneficio1:"beneficio1",b1:"beneficio1",beneficio2:"beneficio2",b2:"beneficio2",beneficio3:"beneficio3",b3:"beneficio3",dia:"dia",motivo:"motivo",comentarios:"comentarios"};params.forEach((value,key)=>{const fieldName=map[key];if(!fieldName||!fields[fieldName])return;const cleanValue=normalizeParam(value);if(fieldName==="tipo"){fields[fieldName].value=cleanValue.toLowerCase()}else{fields[fieldName].value=cleanValue}})}
function updateDynamicFields(){document.querySelectorAll("[data-group]").forEach(group=>{group.classList.toggle("active",group.dataset.group===fields.tipo.value)})}
function updateCounters(){tituloCount.textContent=`${fields.titulo.value.length}/64`;bajadaCount.textContent=`${fields.bajada.value.length}/130`;tituloCount.style.color=fields.titulo.value.length>64?"#ff436e":"#6B7280";bajadaCount.style.color=fields.bajada.value.length>130?"#ff436e":"#6B7280"}
function getDetailsText(){const tipo=fields.tipo.value;if(tipo==="evento"){const parts=[fields.fechaEvento.value&&`Fecha: ${fields.fechaEvento.value}`,fields.horaEvento.value&&`Hora: ${fields.horaEvento.value}`,fields.lugarEvento.value&&`Lugar: ${fields.lugarEvento.value}`].filter(Boolean);return parts.length?parts.join(" · "):"Completá fecha, hora y lugar del evento."}if(tipo==="producto"){const benefits=[fields.producto.value&&`Producto: ${fields.producto.value}`,fields.beneficio1.value,fields.beneficio2.value,fields.beneficio3.value].filter(Boolean);return benefits.length?benefits.join(" · "):"Completá producto y beneficios principales."}const parts=[fields.dia.value&&`Día: ${fields.dia.value}`,fields.motivo.value].filter(Boolean);return parts.length?parts.join(" · "):"Completá día o motivo conmemorativo."}
function adaptDefaultTitle(){const tipo=fields.tipo.value,pais=fields.pais.value;if(fields.titulo.value.trim())return fields.titulo.value;if(tipo==="evento")return"Una invitación para potenciar tus ventas";if(tipo==="producto")return"Soluciones para viajar con respaldo";if(pais==="Uruguay")return"Celebrá cada viaje con nosotros";return"Un mensaje para seguir viajando juntos"}
function updatePreview(){const tipo=fields.tipo.value,partner=fields.partner.value.trim()||"Partner",titulo=adaptDefaultTitle(),bajada=fields.bajada.value.trim()||"La bajada de la pieza se verá acá, con el tono comercial adaptado al país.",cta=fields.cta.value.trim()||"Conocé más";preview.name.textContent=typeLabels[tipo];preview.market.textContent=fields.pais.value;preview.partnerBadge.textContent=partner;preview.title.textContent=titulo;preview.subtitle.textContent=bajada;preview.cta.textContent=cta;preview.details.textContent=getDetailsText();preview.canvas.dataset.type=tipo;updateDynamicFields();updateCounters()}
function getRequestData(){return{estado:"Borrador",tipo:fields.tipo.value,formato:fields.formato.value,pais:fields.pais.value,partner:fields.partner.value,solicitante:fields.solicitante.value,titulo:fields.titulo.value,bajada:fields.bajada.value,cta:fields.cta.value,objetivo:fields.objetivo.value,evento:{fecha:fields.fechaEvento.value,hora:fields.horaEvento.value,lugar:fields.lugarEvento.value},producto:{nombre:fields.producto.value,beneficio1:fields.beneficio1.value,beneficio2:fields.beneficio2.value,beneficio3:fields.beneficio3.value},conmemorativo:{dia:fields.dia.value,motivo:fields.motivo.value},comentarios:fields.comentarios.value,creadoEn:new Date().toISOString()}}
function validateRequest(data){const required=[["país",data.pais],["tipo de pieza",data.tipo],["título",data.titulo],["bajada",data.bajada],["CTA",data.cta]];const missing=required.filter(([,value])=>!String(value||"").trim());return missing.length?`Falta completar: ${missing.map(([label])=>label).join(", ")}.`:""}
function simulateSend(){const data=getRequestData(),error=validateRequest(data);resultBox.classList.remove("hidden");if(error){resultBox.style.background="#FFF1F3";resultBox.style.borderColor="#FECDD6";resultBox.style.color="#B42318";resultBox.innerHTML=`⚠️ ${error}`;return}const requestId=`UA-${Date.now().toString().slice(-6)}`,payload={id:requestId,...data};resultBox.style.background="#ECFDF3";resultBox.style.borderColor="#ABEFC6";resultBox.style.color="#067647";resultBox.innerHTML=`✅ Solicitud lista para enviar a Power Automate.<br>Número de solicitud: <strong>${requestId}</strong><code>${JSON.stringify(payload,null,2)}</code>`;document.getElementById("statusText").textContent="Listo para enviar";document.getElementById("submitTitle").textContent="Solicitud preparada";document.getElementById("submitDescription").textContent="Este JSON será el que luego viaje a Power Automate."}
function copyJson(){const data=getRequestData();navigator.clipboard.writeText(JSON.stringify(data,null,2)).then(()=>{copyJsonBtn.textContent="JSON copiado";setTimeout(()=>copyJsonBtn.textContent="Copiar JSON",1800)})}
function previewImage(input,target,isBackground=false){const file=input.files&&input.files[0];if(!file)return;const reader=new FileReader();reader.onload=event=>{if(isBackground){target.style.backgroundImage=`url(${event.target.result})`}else{target.src=event.target.result;target.classList.remove("hidden");preview.partnerBadge.classList.add("hidden")}};reader.readAsDataURL(file)}
Object.values(fields).forEach(field=>{if(!field||field.type==="file")return;field.addEventListener("input",updatePreview);field.addEventListener("change",updatePreview)});fields.logoPartner.addEventListener("change",()=>previewImage(fields.logoPartner,preview.partnerLogo));fields.imagenFondo.addEventListener("change",()=>previewImage(fields.imagenFondo,preview.bg,true));sendBtn.addEventListener("click",simulateSend);copyJsonBtn.addEventListener("click",copyJson);loadFromUrl();updatePreview();
